### ISSUE TITLE
ArchLinux package (AUR)

### ISSUE THREAD

**Issue by sxiii** [hardinfo2/hardinfo2#10]
Seems to build OK but I think the binaries are not getting installed correctly. Probably the package() function should be fixed.

So needs a little bit of work. So far,

PKGBUILD:
```
# Packager: Den Ivanov <securityxiii at gmail dot com>

pkgname=hardinfo
pkgver=2.0.12
pkgrel=0
pkgdesc="System Information and Benchmark for Linux Systems."
arch=('x86_64')
url="https://github.com/hardinfo2/hardinfo2"
license=('GPL2')
depends=('gtk3' 'zlib' 'glibc' 'libsoup')
source=(https://github.com/hardinfo2/hardinfo2/releases/download/release-2.0.12/hardinfo-2.0.12-Source.tar.gz)
md5sums=('07923bfb31d68ef01b95423eaebbff77')

build() {
  cd ${srcdir}/${pkgname}-${pkgver}-Source
  ls
  cmake -DDISTRO=1 -DMAINTAINER="Den Ivanov securityxiii@gmail.com"
  make package
  make package_source
}

package() {
  cd ${srcdir}/${pkgname}-${pkgver}-Source
  make DESTDIR=${pkgdir} install
  install -d -m755 ${pkgdir}/usr/share/applications
  cd "${pkgdir}/usr/share/applications"
}

```
.SRCINFO:
```
pkgbase = hardinfo
	pkgdesc = System Information and Benchmark for Linux Systems
	pkgver = 2.0.12
	pkgrel = 0
	url = https://github.com/hardinfo2/hardinfo2
	arch = x86_64
	license = GPL2
	depends = gtk3 zlib glibc libsoup
	source = https://github.com/hardinfo2/hardinfo2/releases/download/release-2.0.12/hardinfo-2.0.12-Source.tar.gz
	md5sums = 07923bfb31d68ef01b95423eaebbff77

pkgname = hardinfo
```
Build as: enter the directory with two files and run "makepkg" (being on Arch/Garuda/Manjaro).
Install: sudo pacman -U hardinfo*

**Comment by hwspeedy** [comment]
@sxiii Good start - I do unfortunately have no knowledge about packing in Arch Linux. I have tested it on arch with "make -j;make install" - which messes up your distro - not recommended!!

License is GPL2+

make package - uses CPACK and creates the binary package for RPM/DEB. It seams the CPACK for Arch is not done - so not supported for arch yet...

make package_source - also uses CPACK and creates new source package zip files.

Does arch have a suggest package feature?
suggest these: lm-sensors sysbench lsscsi mesa-utils dmidecode udisks2 xdg-utils iperf3

Maybe others can help creating source and binary packages for Arch Linux?

**Comment by hwspeedy** [comment]
@bbidulock 

Have sent an email to Brian Bidulock - original Arch Linux packaging maintainer.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hardinfo

**Comment by hwspeedy** [comment]
@yochananmarqos

Seams there is a newer package maintainer in Arch Linux AUR for hardinfo.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hardinfo-git

Maybe Mark Wagie wants to help or package hardinfo2 for Arch Linux?

**Comment by yochananmarqos** [comment]
@hwspeedy I have no idea what you're referring to. What "newer package maintainer"?

**Comment by hwspeedy** [comment]
Hi @yochananmarqos,

Hardinfo2 is a community reboot of hardinfo, that has not been released for >10 years. 

https://www.hardinfo2.org/

This is the organization starting to build up around community edition: https://github.com/hardinfo2/hardinfo2/discussions/16

We just made a first release:
https://github.com/hardinfo2/hardinfo2/releases/tag/release-2.0.12

Would you like to either help @sxiii with packaging for AUR or be the package maintainer for Arch Linux?

Coordinating Linux Arch AUR: https://github.com/hardinfo2/hardinfo2/issues/10

**Comment by yochananmarqos** [comment]
@hwspeedy Oh, sorry. I was distracted when I answered and didn't realize you had tagged me in the hardinfo2 repo.

AUR packages build with `libsoup3` are done:

* [`hardinfo2`](https://aur.archlinux.org/packages/hardinfo2)
* [`hardinfo2-git`](https://aur.archlinux.org/packages/hardinfo2-git)

I really don't see the point of using the `DISTRO` and `MAINTAINER` flags, however I will use them if you want.

**Comment by hwspeedy** [comment]
@yochananmarqos 

Wau that was fast! 👍 

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hardinfo2

Are you missing depends?
debian depends: libjson-glib-dev zlib1g-dev libsoup2.4-dev libgtk-3-dev libglib2.0-dev

Does arch have a suggest package feature?
suggest these: lm-sensors sysbench lsscsi mesa-utils dmidecode udisks2 xdg-utils iperf3

It seams that **libsoup3** works fine, but there might be issues - being Arch Linux - I think the users can manage that. :)

**hardinfo2-git is unstable** and can break at any time - but guess that everyone knows that at Arch Linux.

Please note this issue: https://github.com/archlinuxcn/repo/issues/3682

When Fedora and Debian are done accepting the package, we do a new release with the changes.

**Comment by yochananmarqos** [comment]
> Are you missing depends?

Well, I suppose technically I'm missing the transitive dependencies, however `gtk3` and `libsoup3` covers them all.

`namcap` output from `hardinfo2`:

```
hardinfo2 I: Depends as namcap sees them: depends=(cairo gdk-pixbuf2 glib2 libsoup3 glibc json-glib libx11 pango lm_sensors gtk3 hicolor-icon-theme)
```

> suggest these: lm-sensors sysbench lsscsi mesa-utils dmidecode udisks2 xdg-utils iperf3

Ah, forgot about some of those that `namcap` doesn't detect and aren't required during build. I'll add them.

> It seams that libsoup3 works fine, but there might be issues

Well, for now the stable `hardinfo2` package can depend on `libsoup` while `hardinfo2-git` can depend on `libsoup3` since it's still marked experimental.

**Comment by yochananmarqos** [comment]
> What about controlling packages that overwrite each others files in Arch Linux?

The hardinfo2 packages do not have any conflicting files with the original hardinfo. I have both `hardinfo-git` and `hardinfo2-git` installed right now. One can only have `hardinfo2` or `hardinfo2-git` installed at a time as they both provide and conflict with `hardinfo2`.

> lm-sensors sysbench lsscsi mesa-utils dmidecode udisks2 xdg-utils iperf3

I've added most of those as optional dependencies.

**Comment by hwspeedy** [comment]
Very good - lets see what users say - Thanx alot 🥇

**Comment by yochananmarqos** [comment]
You're welcome. I'm off to relax for the evening. :wave:

**Comment by yochananmarqos** [comment]
@hwspeedy Thanks for the invitation to join the organization. However, I don't want notifications enabled by default for every tiny little thing. Anyone can ping me if there's any package related issues regardless.

By the way, this issue can be closed.

**Comment by hwspeedy** [comment]
@yochananmarqos 

Working great with packaging in arch branches, thanx alot.

Is it possible to also get the hardinfo2 app into pacman for easier access for users?

PS: maybe hardinfo should change to hardinfo2 see https://github.com/lpereira/hardinfo top of readme?

**Comment by yochananmarqos** [comment]
> Is it possible to also get the hardinfo2 app into pacman for easier access for users?

See [How to get a PKGBUILD into the extra repository?](https://wiki.archlinux.org/title/Arch_User_Repository#How_to_get_a_PKGBUILD_into_the_extra_repository?)

> maybe hardinfo should change to hardinfo2

I've submitted requests to merge `hardinfo` into `hardinfo2` and `hardinfo-git` into `hardinfo2-git`.

**Comment by hwspeedy** [comment]
@yochananmarqos,

Thank you so much for your fine work with hardinfo2. 

Can we change AUR to use CMAKE_BUILD_TYPE=Release instead of None, thanx.

The reason that is not mentioned on the README.md build instruction, is to could identify self builds from distro builds - for the benchmark part to validate and rank distro builds higher in confident.

I have put the build instruction on the release page under release info:
https://github.com/hardinfo2/hardinfo2/releases/tag/release-2.1.2

**Comment by yochananmarqos** [comment]
Done. What's with the `99_` at the end?

```
-- Found no distro version - Using codename
-- Found Package Version 2.1.2
-- Found distro description ArchLinux99_
```

**Comment by hwspeedy** [comment]
@yochananmarqos 

Thanx,

The 99 is for sid/unstable/non versioned from /etc/os-release - it is only used for CPack package file names, which are not used by Arch.

Check the file names of packages built with CPack in attachment:
https://hardinfo2.org/github?latest_prerelease

PS: Package name is always hardinfo2.

Is it a problem for Arch?

**Comment by yochananmarqos** [comment]
No problem, I was just curious.
