### ISSUE TITLE
memory devices not shown and hint empty

### ISSUE THREAD

**Issue by seniordevel** [hardinfo2/hardinfo2#103]
Viewing 'Memory devices' results in 'Not available - see hints below', but hint box is empty,
It is not a colour/contrast issue, the hint box works fine with other devices.

![Screenshot_20241029_221856](https://github.com/user-attachments/assets/4d4749ab-e7ac-4087-9953-efde6c27a974)

System Information
Linux 6.10.13-3-MANJARO (x86_64),
KDE on x11

HardInfo2 2.2.1

**Comment by hwspeedy** [comment]
Thanx @seniordevel,

It's a duplicate of this one: https://github.com/hardinfo2/hardinfo2/issues/99

Please try the hardinfo2-git instead of hardinfo2 from AUR, that includes the fix.

**Comment by seniordevel** [comment]
Thank you, Git version works

**Comment by hwspeedy** [comment]
Left open for info - until next release.
