### ISSUE TITLE
[question] - can we use "CMAKE_SYSTEM_PROCESSOR" instead of "CMAKE_HOST_SYSTEM_PROCESSOR" in CMakeLists.txt?

### ISSUE THREAD

**Issue by r-a-sattarov** [hardinfo2/hardinfo2#116]
Hi everyone!

The question is related to the fact that I cross-compile Hardinfo2 (build for e2k on x86).
In such situations, the variable `CMAKE_HOST_SYSTEM_PROCESSOR` is equal to x86, and the variable `CMAKE_SYSTEM_PROCESSOR` is equal to e2k.

Because of this, the  `HARDINFO 2_ARCH` variable becomes equal to x86, and the program for e2k is assembled incorrectly (the code for x86 is used instead of the code for e2k).

Is it possible to switch to using the `CMAKE_SYSTEM_PROCESSOR` variable instead of `CMAKE_HOST_SYSTEM_PROCESSOR` in CMakeLists.txt?

**Comment by hwspeedy** [comment]
@r-a-sattarov 

Very nice finding, Thanx.

CMAKE_SYSTEM_PROCESSOR is defined in CMAKE v3.0.2->v3.31.0+:
https://cmake.org/cmake/help/v3.0/variable/CMAKE_SYSTEM_PROCESSOR.html

Patch will be in next release.

**Comment by r-a-sattarov** [comment]
Thank you very much!
