### ISSUE TITLE
[FR] - used version of libsoup / gtk in output of hardinfo2 version?

### ISSUE THREAD

**Issue by r-a-sattarov** [hardinfo2/hardinfo2#119]
Is it possible to add the version of used libsoup library in the output of hardinfo2 version?
Maybe also add a used version of the gtk library? This would be useful for bug reporting.

**Comment by hwspeedy** [comment]
You can already see version and other build options like libsoup version with:
hardinfo2 -v

gtk version 2 is unmaintained and therefore dead and should never be used on any distro.

**Comment by r-a-sattarov** [comment]
> You can already see version and other build options like libsoup version with:
> hardinfo2 -v

Thanks, I didn't know about this option.
