### ISSUE TITLE
Info banners unreadable on dark themes

### ISSUE THREAD

**Issue by bbeckoo** [hardinfo2/hardinfo2#22]
This was an issue forever. When using a dark theme the info banner background stays bright with bright text on it
![2024-04-09-095324_screenshot](https://github.com/hardinfo2/hardinfo2/assets/634297/6d2b8662-8443-4d68-8bb8-baf98423b191)

**Comment by hwspeedy** [comment]
Thanx for reporting -  Changed the background color of note to match color scheme for hardinfo2. Now readable in both light and dark mode. 

https://github.com/hardinfo2/hardinfo2/commit/e970960ecfbca469b2dc1638ac3a26517291e722

**Comment by bbeckoo** [comment]
Now the light theme is broken :)

![2024-04-09-132849_screenshot](https://github.com/hardinfo2/hardinfo2/assets/634297/bb7ec7b1-a6ee-47b4-a848-cd44014f32be)

**Comment by hwspeedy** [comment]
It's readable on debian12, fedora39, ubuntu22(WSL) - But they are different text colors - also gamma and contrast settings for screen matter. 
Remember to test app focus/not focus also.

For me it is as readable as the black on gray in dark mode.

We can make the background a little lighter... (higher values) - Can you try changing the bg color values for your setup and send those values, thanx.

**Comment by hwspeedy** [comment]
I have set the foreground color as fixed also - seams to be the right thing to do as the background color is fixed. Now it is blue background with white text in both modes.

**Comment by bbeckoo** [comment]
Yes, a lot better, though now I find this blue a little too strong, maybe the original colors with black text?

**Comment by hwspeedy** [comment]
It's meant to stand out from the rest of the app - it's the white that makes it so strong - high contrast. I have lowered the contrast. Thanx for reporting and thanx for feedback - now at least we can all read the text notes.

**Comment by bbeckoo** [comment]
I still think, it's a bit too much intrusive, but now it's functional and visible on all kind of backgrounds. 
Thank you for keeping this project alive.
