### ISSUE TITLE
HardInfo2 all entrys missing except Network

### ISSUE THREAD

**Issue by Gravarty** [hardinfo2/hardinfo2#25]
For some reason HardInfo2 only shows Network connection stuff on my install (Arch Linux / AUR) 2.0.18

![Bildschirmfoto zu 2024-04-22 16-59-24](https://github.com/hardinfo2/hardinfo2/assets/16298668/077611b6-2ebe-4f85-a585-0e3c0bad94bc)

all dependencies etc. are installed  and working.

**Comment by hwspeedy** [comment]
My best guess is that you have remedies from older hardinfo installed. Have you had hardinfo installed? - perhaps using "make install" to /usr/local and maybe other places?

YES: Try to clean by doing something like this:
https://github.com/hardinfo2/hardinfo2/blob/master/tools/rm_hardinfo.sh
perhaps reboot to clear libs
Then reinstall hardinfo2 AUR.
hardinfo2

NO: no idea...

Anyone using arch and German locale? - Is it working or a translation error?

**Comment by hwspeedy** [comment]
cannot reproduce - no return answer.
