### ISSUE TITLE
diagnose pc problems over the network

### ISSUE THREAD

**Issue by pannet1** [hardinfo2/hardinfo2#26]
hi, is there a way to diagnose pc problems over the network. i get that it is not the objective of hardinfo. motivation is to tell remote user to connect with just a working network and bios.

**Comment by hwspeedy** [comment]
Hi @pannet1,

You can ask the user to run a terminal command or use SSH if you have that access to the PC.

**Eq. Show the BIOS version:**
"hardinfo2 -r -s -q|grep -A3 ^\-BIOS"

We will probably work more on the CLI interface in the future to do something like "hardinfo2 -t BIOS"
(NOT IMPLEMENTED YET!!)

If you want a full report and have some way for the user to sent it to you - that is possible from command line.
hardinfo2 -r -s -q >somefile.txt
scp ./somefile.txt LOGINS@YOURHOST:/PATH/


Is that what you are talking about?

**Comment by hwspeedy** [comment]
Question not explained - No reply.

**Comment by pannet1** [comment]
sorry for late reply. I was expecting to run hwinfo on a failed hardware, wondering what will be the minimum requirement for any diagnostics to work. assuming there is a working network card and bios . we wan to find out which other hardware failed (cpu, vga, motherboard, ram, storage)

if network booting is selected as a failsafe method of booting, it would take them to a server that would do what it takes to scan the client and probably mail the diagnostics.

assumption is here the user is novice and probably running *do?s

**Comment by hwspeedy** [comment]
@pannet1 

That won't work 
- if the cpu is not working, no OS (operating system) can start.
- if no VGA - no output for the user
- if motherboard failed - no OS can start
- if no RAM - no OS can start
- if storage is faulty - no OS can start.

You can diagnose missing/outdated software and BIOS configurations, missing firmware upgrades. See what hardware is installed and offer upgrades to run a particularly demanding software/game/etc.

**Comment by pannet1** [comment]
got it. 

another use case is i am having 100s of same kind of used laptop .. is it possible to diagnose them over the network .. if the hardware is having capabilities as it is claimed

**Comment by hwspeedy** [comment]
You can create a golden sample and compare the other machines to the golden sample - not sure if you will spot defect, but it is better than no testing.

Old laptops mostly cannot boot (Bad HD/Overheated and burned) or has a bad battery - The benchmark is probably to short to spot thermal problems - but old laptops should all be cleaned and repasted for CPU & GPU.

OS is just any Linux distro.
