### ISSUE TITLE
List of environment variables not sorted alphabetically

### ISSUE THREAD

**Issue by rizalmart** [hardinfo2/hardinfo2#27]
Can you please make list of environment variables sort alphabetically in order to make looking for specific environment variables easier upon click the ENVIRONMENT VARIABLES on the sidebar?

**Comment by hwspeedy** [comment]
Yes, that is a very good suggesting, thanx.

**Comment by hwspeedy** [comment]
@rizalmart 

Implemented in master - Will be in next release, thanx.
