### ISSUE TITLE
Redundant entries on list of users and groups

### ISSUE THREAD

**Issue by rizalmart** [hardinfo2/hardinfo2#28]
The entries of users and groups section repeats twice.  Please fix it

**Comment by hwspeedy** [comment]
I do not see duplets for users/groups - please send more info for reproduction, thanx.

But they are also not sorted - that could be improved.

**Comment by hwspeedy** [comment]
Users sorted: https://github.com/hardinfo2/hardinfo2/commit/47b8c66bb26c1a60aba8aa31774c2e6bdfb7140c

Groups sorted by group name: https://github.com/hardinfo2/hardinfo2/commit/7a55301afc255119bc0b5bcd0ec411f8151d4802

I think it is better to sort by group name - the GID is just an internal number, which is not important for users...

**Comment by hwspeedy** [comment]
@rizalmart - Waiting for more info to reproduce the duplets errors in users/groups sections.

**Comment by hwspeedy** [comment]
Not reproducible - No answer.
