### ISSUE TITLE
GPU name not specific for model - PCIe/DRM/Mesa different info

### ISSUE THREAD

**Issue by utherbone** [hardinfo2/hardinfo2#29]
Here:
![image](https://github.com/hardinfo2/hardinfo2/assets/13210391/73a08d73-8a16-4f62-9d34-8e63f3397d2b)

Using `glxinfo -B` the name display is correct.
![image](https://github.com/hardinfo2/hardinfo2/assets/13210391/603612cc-3ac4-46c4-8e5d-950cde688f4f)

Using `lspci | grep ' VGA '` also appears incorrect
![image](https://github.com/hardinfo2/hardinfo2/assets/13210391/d239a84b-6553-42b7-8a78-d587ba998a9b)

Is this a lack of information/bug in the Linux GPU or in the software?

Thanks for the support.

**Comment by hwspeedy** [comment]
Could be some difference between pcie subsystem reporting, driver reporting and mesa reporting?

Any one, who can look into this, thanx.

**Comment by hwspeedy** [comment]
@utherbone 
I looked into the way the hardinfo2 program works with Linux for graphics cards model names.

The Open GL Renderer is more card specific for the model edition (glxinfo -B ->Device), than the pci device data and dri driver name. 

**The Open GL Renderer device name info is actually shown under Computer->Display->OpenGL (GLX)->Renderer.**

As there can be more PCIe Graphics cards, the OGL_Render information cannot just be put into the graphics card info...

So yes, it is not consistent from pcie model names, driver card names to Open GL Render. Which is kind of normal and I think the way we show the information is the best we can do.

What is your opinion / suggestions?

**Comment by utherbone** [comment]
Sorry, I don't understand much about this level of programming yet, but I can help with logs and any tests, and just provide me with instructions that I run and post the results here to help with that if it can be opened.
I completely forgot to check github notifications.

**Comment by hwspeedy** [comment]
In your case, you get a more accurate model description of your graphics card in hardinfo2 under Computer->Display->OpenGL (GLX)->Renderer.

But on notebooks with integrated Intel graphics, that is not the case.

So conclusion: **We cannot do better.**

**Comment by utherbone** [comment]
Okay, thanks a lot, and in the near future maybe I can contribute in code, I'm still in the first year of graduation in Computer Engineering!

**Comment by hwspeedy** [comment]
@utherbone 
Super nice, good choice to take a good education!
Stick around and have fun, but school comes first - then you can help your fellow people with nice products. 👍
