### ISSUE TITLE
error during PKGBUILD

### ISSUE THREAD

**Issue by joshwisehub** [hardinfo2/hardinfo2#30]
Distro: Archlinux 6.8.9  on wayland

makepkg -cis
==> ERROR: PKGBUILD does not exist.

**Comment by hwspeedy** [comment]
Send more info, what you are doing on arch Linux. Something is wrong in your procedures or setup...

**Comment by joshwisehub** [comment]
i followed the instructions on how to install it in archlinux and at that point is where the error occured
![image](https://github.com/hardinfo2/hardinfo2/assets/82163087/76b8d34f-0285-479f-8908-a402698f9eaa)

**Comment by hwspeedy** [comment]
Thanx for more info.

I am pretty sure something went wrong before makepkg -cis
Maybe you checked out this repo instead of the AUR repo?

**ArchLinux/Garuda/Manjaro - AUR Package**
git clone https://aur.archlinux.org/hardinfo2
cd hardinfo2
makepkg -cis
hardinfo2

**Comment by hwspeedy** [comment]
Not reproduceable - users error - no answer.
