### ISSUE TITLE
Consider raising CMake version requirement and drop compat with ancient Linux distributions

### ISSUE THREAD

**Issue by hosiet** [hardinfo2/hardinfo2#36]
I am reviewing the current hardinfo2 CMake build system, and noticed several carried-over burdens due to the choice of an ancient CMake standard (currently `3.0.0`). If we agree that the future hardinfo2 releases do not want to support EOLed Linux distributions releases, we could reasonably raise the bar of CMake version requirements.

My current proposal on minimum supported OS versions is as follows:

* Debian (>= 10): cmake 3.13.4+
* Ubuntu (>= 14.04): cmake 3.5.1+
* Ubuntu (>= 18.04): cmake 3.10.2+
* CentOS and RH derivatives (>= 8): cmake 3.20.2+
* Fedora (>= 35): cmake 3.24.2+

As a result, a satisfactory minimum cmake compatibility version would be 3.10.2. A more conservative choice would be 3.5.1.

This would drop native CentOS 7 support. CentOS 7 will be EOL on 2024-06-30. But since CentOS 7 only ships cmake 2.8.12 and that we already don't have native support for it, there is nothing to lose. Building packages on CentOS 7 will need 3rdparty cmake binaries anyway.

With a higher cmake standard, I would expect to first drop the `cmake/GNUInstallDirs.cmake` file, which is built-in to CMake after 3.0.2. Further CMake refactoring would also be easier.

**Comment by topazus** [comment]
> With a higher cmake standard, I would expect to first drop the `cmake/GNUInstallDirs.cmake` file, which is built-in to CMake after 3.0.2.

Agreed here.

**Comment by hwspeedy** [comment]
Thanx @hosiet, 

We need to move to CMake>=3.5 as instructed by CMake team, but it is not needed yet - AFAIK.

I Suggest to first get the hardinfo2 app into every distro again and get it build by third party repos for as many old distros as possible: Debian 7,8,9 branches and fedora 23-35, centos 6,7 branches, then we can cut off old distros, when it's actually needed with minimal damage.

**Comment by topazus** [comment]
Is there really a need that the latest of hardinfo2 still supports the Linux distribution, which is already EOL (end of life)? They can use the specific old release that satisfies.

**Comment by hwspeedy** [comment]
What would you gain by drop support for non active maintained distros now?

PS: Remember there is no old release for the last 14 years - it has been unstable git versions or distro fixed versions and even the old releases are unstable and missing features.

**Comment by hwspeedy** [comment]
Updated cmake required version to 3.0.2 and removed local GNUInstallDirs.cmake

https://github.com/hardinfo2/hardinfo2/commit/f55220d661ce66cba5d1ac35cf2310f08b900c9d

All tested distro still builds and works - Above 3.0.2 distros will start falling short...

**Comment by Kieltux** [comment]
Just here to put the info for openSUSE and cmake versions in:

- openSUSE Leap 15.5: cmake 3.20.4
- openSUSE Leap 15.6: cmake 3.28.3
- openSUSE Tumbleweed: cmake 3.29.3

So cmake 3.0.2 would be save.

**Comment by topazus** [comment]
> What would you gain by dropping support for non actively maintained distros now?

Well, I do not gurantte that it will benefit much with dropping the support for old distros. I am just a Fedora Linux user, which it will introduce plenty of new updates and publish new release every six months.

**Comment by hwspeedy** [comment]
Yes, that's the normal nature of every distro branch. 

Fast paged distros in front and later down the stream, the distros used by people not upgrading all the time. We will support them all as good as possible for as long as possible.

**Please help to do this as a package maintainer - update the long life cycle distros for as long as possible.**

RHEL7 has 4 more years before EOL.
https://www.redhat.com/en/blog/announcing-4-years-extended-life-cycle-support-els-red-hat-enterprise-linux-7

Ubuntu LTS 14.04 has 2 more years before EOL
https://wiki.ubuntu.com/Releases

**Comment by hwspeedy** [comment]
Closed for now - later change CMake to 3.5, when needed.
