### ISSUE TITLE
hardinfo2 - OpenMandriva Packaging

### ISSUE THREAD

**Issue by hwspeedy** [hardinfo2/hardinfo2#39]
@AngryPenguinPL

Do you want to package hardinfo2 - community rebooted hardinfo for OpenMandriva official repos?

Webpage:
https://hardinfo2.org

Project:
https://github.com/hardinfo2/hardinfo2

PS: It is already in Fedora/Redhat, so should be pretty easy.
PPS: The old hardinfo git repo is being decommissioned.

In advance thanx,

/hwspeedy

**Comment by hwspeedy** [comment]
Thanx for the incredible fast and great work!

**Comment by hwspeedy** [comment]
Hi @AngryPenguinPL ,

I am trying to get all possible distros up2date on version 2.1.11 to ensure we have a working base for all distros.

**Is it possible to update OpenMandriva 5.0 to hardinfo2 version 2.1.11?**

In advance thanx.

**Comment by AngryPenguinPL** [comment]
> Hi @AngryPenguinPL ,
> 
> I am trying to get all possible distros up2date on version 2.1.11 to ensure we have a working base for all distros.
> 
> **Is it possible to update OpenMandriva 5.0 to hardinfo2 version 2.1.11?**
> 
> In advance thanx.

Done, package for 5.0 updated. It should take a bit time until repology refresh database.

**Comment by hwspeedy** [comment]
@AngryPenguinPL 

Thanx for all your help,

1. I finally came around to installing OpenMandriva and got the distro logos and vendor url added. As I see it, this distro is totally independent of RedHat and Fedora now - since RH5.1.
git patch for next: https://github.com/hardinfo2/hardinfo2/commit/5f56a2fb22d147d99f00b5d7edadc1dfa8a657fc

![image](https://github.com/user-attachments/assets/7c339f4e-3316-43db-9560-993890fa2119)
Fixed Distribution - You are welcome to add this patch now, if you like.

2. The sysbench in OpenMandriva is compiled in a wrong way - the results are bogos (x10) - probably clang/llvm diff - so to could use sysbench in OpenMandriva to compare to other distros, the package should be updated.

This fixes the sysbench 1.0.20 package:
```
git clone https://github.com/akopytov/sysbench --branch 1.0
cd sysbench
./autogen.sh
./configure --without-mysql CC=gcc
make -j
```

**Comment by berolinux** [comment]
> 1. I finally came around to installing OpenMandriva and got the distro logos and vendor url added.

Thanks, much appreciated.

> As I see it, this distro is totally independent of RedHat and Fedora now - since RH5.1.

Yes, while we occasionally "steal" patches from them (and Arch and Debian and *BSD and others...), we've been independent for a long time.

> 2. The sysbench in OpenMandriva is compiled in a wrong way - the results are bogos (x10) - probably clang/llvm diff - so to could use sysbench in OpenMandriva to compare to other distros, the package should be updated.

Do you have any idea why? This _could_ be a bug, but it's also quite possible that the benchmark they use to determine the score simply happens to be optimized much better when built with clang (usually there's not that much of a difference in performance, but there are some tests that can show clang built code actually being 10 times faster, and some other tests that can show gcc built code being 10 times faster -- both compilers have their particular strengths and weaknesses).

**Comment by hwspeedy** [comment]
> Do you have any idea why? This could be a bug, but it's also quite possible that the benchmark they use to determine the score simply happens to be optimized much better when built with clang (usually there's not that much of a difference in performance, but there are some tests that can show clang built code actually being 10 times faster, and some other tests that can show gcc built code being 10 times faster -- both compilers have their particular strengths and weaknesses).


Probably has to do with LuaJit implementation - The Lua usage should result in unoptimized code for benchmarks. So does not matter if it is clang/llvm or gcc - same result +/-5% should be achieved. 
The sysbench project is kind of death for now - but we can use the unoptimized results of 1.0.20 to compare the CPUs across all Linux distros.

**Comment by AngryPenguinPL** [comment]
Fixed sysbench and also applied patch to hardinfo.
Thanks.
