### ISSUE TITLE
new hardinfo2 web page and server of storage for  data

### ISSUE THREAD

**Issue by mckaygerhard** [hardinfo2/hardinfo2#4]
to not disturb the original domain and welcome the alternate project... a repo was created

For those who don't know... **hardinfo2/hardinfo sends data (if the user wishes/command) to a server**, this is used **to have better knowledge of the hardware present**, and thus improve technical support as well as the support of the Linux system, making this data shareable

This issue is to discuss the needs:

-   data synchronization
-   web design
-   format and privacy involved in saving data
-  conquest to participants on making a new web page

discussion shoul be into https://github.com/hardinfo2/hardinfo2/discussions/3 .. here only will be specific things about the PR ( by example we have 3 participants and so then 3 PR .. here we will post only things respect those PRs)

Pull request shoul be in own repository: https://github.com/hardinfo2/server/pulls

**Comment by hwspeedy** [comment]
@mckaygerhard

**Please keep issues for server on the server repo: https://github.com/hardinfo2/server/issues**

**PS: We have only one place for discussions, that is to keep us all together: https://github.com/hardinfo2/hardinfo2/discussions**

Right now I see no use for wiki - The users should go to project webpage lead by "server team".
- In the future I would like the wiki to contain development guides - use gdb/valgrind/asan like this, the code overview is like, how to program for for many library versions, - SERVER: We update database like this, etc.
