### ISSUE TITLE
PCLinuxOS Building/Packaging

### ISSUE THREAD

**Issue by hwspeedy** [hardinfo2/hardinfo2#48]
PCLinuxOS Building
----------
apt install git cmake gcc gcc-c++ gettext rpmdevtools curl
apt install json-glib-devel zlib-devel lib64soup3-devel gtk3-devel lib64tiff-devel lib64glvnd-devel
git clone https://github.com/hardinfo2/hardinfo2
cd hardinfo2
./tools/git_latest_release.sh       **(CHANGE TO LATEST RELEASE - BUT IT NEEDS THIS PATCH: https://github.com/hardinfo2/hardinfo2/commit/3df32fc9b002618e5d73de08d3a50d3cc129c123 or just don't run this command and build latest unstable from git master)**
mkdir build
cd build
cmake ..
make package -j
apt install ./hardinfo2-*
apt install lm_sensors lsscsi dmidecode udisks2 xdg-utils iperf

**Missing recommended packages FIXME: sysbench, glx-utils, fwupd**

![image](https://github.com/hardinfo2/hardinfo2/assets/17836636/4a94a210-ee5c-4e21-8929-55ea9ff393bd)

From downloads:
https://github.com/hardinfo2/hardinfo2/releases/download/release-2.1.10pre/hardinfo2-2.1.10-PCLinuxOS-2024.x86_64.rpm

**If anyone would like to package hardinfo2 for PCLinuxOS - Just give a ping here, thanx**

**Comment by hwspeedy** [comment]
hi @terryn94

hardinfo has been unmaintained for long time but now we have released a new community version.

Last 14 years upstream was here https://github.com/lpereira/hardinfo - and now transferred here to community edition as written in lpereira's README.md.

Would you be interested in updating PCLinuxOS with hardinfo2 package instead of old unmaintained hardinfo?

Project homepage: https://hardinfo2.org
PCLinuxOS packaging: https://github.com/hardinfo2/hardinfo2/issues/48
Release notes: https://github.com/hardinfo2/hardinfo2/releases/tag/release-2.1.11
Github: https://github.com/hardinfo2/hardinfo2/

In advance thanx,

/hwspeedy

**Comment by terryn94** [comment]
Ok I will take a look ;-)

**Comment by terryn94** [comment]
I'm struggling to get this working.  Have tried building from 2.1.11 tar ball, 2.1.0pre as illustrated above and also from git master.
I end up with an empty screen.  I have dmidecode, iperf, lm_sensors, lsscsi, pciutils, udisk2 and xdg-utils installed.
However, your linked rpm works.  Confused :-(
![Screenshot_20240623_163829a](https://github.com/hardinfo2/hardinfo2/assets/135114324/ce0511eb-1225-43b4-90af-1bb68beaa67f)

**Comment by hwspeedy** [comment]
Please have a look at spec file from fedora/redhat. Probably missing som updates to your spec file.

**Comment by hwspeedy** [comment]
Any luck building it using pclinux package building?

This is the spec fule for fedora from topazus:
https://src.fedoraproject.org/rpms/hardinfo2/tree/rawhide

What building system does pclinux use? Koji clone?

**Comment by terryn94** [comment]
No, I'm still just getting a blank window.  My SPEC is the same as Fedora and Mageia.  
We don't have mock or Koji, we just create a SPEC and run rpmbuild on it.

**Comment by hwspeedy** [comment]
> No, I'm still just getting a blank window.  My SPEC is the same as Fedora and Mageia.  


It must have something to do with the modules not being found/installed correctly or that you have old hardinfo/used make install. Check tools for clean up script and check where eg. network.so is located and compare with hardinfo2 -v

**Comment by terryn94** [comment]
`[terry@acer885 rpm]$ hardinfo2 -v
Hardinfo2 version 2.1.12
Copyright (C) 2003-2023 L. A. F. Pereira. 2024-2024 Hardinfo2 Project.

Compile-time options:
  Release version:   No (2.1.12) (ARCH_x86)
  LibSoup version:   3.0
  BinReloc enabled:  Yes
  Data prefix:       /usr/share/hardinfo2
  Library prefix:    /usr/usr/lib64/hardinfo2
  Locale prefix :    /usr/share/locale
  Data hardcoded:    /usr/share/hardinfo2
  Library hardcoded: /usr/lib64/hardinfo2
  Locale hardcoded:  /usr/share/locale
  Compiled for:      PCLinuxOS-ARCH_x86`

[terry@acer885 rpm]$ ls -l /usr/lib64/hardinfo2/modules/
total 500
-rwxr-xr-x 1 root root 111160 Jun 24 10:58 benchmark.so*
-rwxr-xr-x 1 root root  98136 Jun 24 10:58 computer.so*
-rwxr-xr-x 1 root root 259808 Jun 24 10:58 devices.so*
-rwxr-xr-x 1 root root  35664 Jun 24 10:58 network.so*


The SPEC uses %cmake_install (as do Fedora and Mageia) which expands to:
`/usr/bin/make install DESTDIR=/home/terry/src/rpm/BUILDROOT/%{NAME}-%{VERSION}-%{RELEASE}.x86_64 INSTALL="/usr/bin/install -p" -C build`

The only difference I have spotted between my built RPM and the one you supplied is that mine doesn't appear to have linked
libatk-1.0.so.0()
libharfbuzz.so.0()
even though those libraries (and their -devel packages) are installed at build time.

**Comment by hwspeedy** [comment]
We saw something similary when using Ninja on older linux systems, that the libharfbuzz was not linked in. Result is missing fonts. That could be the blank page.

Why does hardinfo2 -v say it is not a release build. -DMAKE_BUILD_TYPE=Release should be set in spec file. It is in fedora. Maybe some naming epel vs pclinux in spec file.

**Comment by terryn94** [comment]
Ok fixed the release build but still have the same issue.

[terry@acer885 SPECS]$ hardinfo2 -v
Hardinfo2 version 2.1.12
Copyright (C) 2003-2023 L. A. F. Pereira. 2024-2024 Hardinfo2 Project.

Compile-time options:
  Release version:   Yes (2.1.12) (ARCH_x86)
  LibSoup version:   3.0
  BinReloc enabled:  Yes
  Data prefix:       /usr/share/hardinfo2
  Library prefix:    /usr/usr/lib64/hardinfo2
  Locale prefix :    /usr/share/locale
  Data hardcoded:    /usr/share/hardinfo2
  Library hardcoded: /usr/lib64/hardinfo2
  Locale hardcoded:  /usr/share/locale
  Compiled for:      PCLinuxOS-ARCH_x86

I'll continue to look into the libharfbuzz thing as it's the only lead I have.

**Comment by hwspeedy** [comment]
disable ninja building if using that. Fedora uses Ninja, but epel (older releases) does not.

**Comment by terryn94** [comment]
OK got it sorted.
Sent hardinfo2-2.1.11 to go in the PCLinuxOS repository

**Comment by hwspeedy** [comment]
Thanx, good job!

**Comment by hwspeedy** [comment]
@terryn94 

I had some fun with the PC Linux OS distro, quite nice and fast!! :)

**For hardinfo2 we are missing a couple of packages:**
1. sysbench - Maybe you can add sysbench to pclinuxos hardinfo2 package with attached script.
[build_and_install_sysbench.sh.txt](https://github.com/user-attachments/files/17027593/build_and_install_sysbench.sh.txt)

2. fwupd package - Should be added as real package - it's great! - until then you can use attached script & service.
[build_and_install_fwupd.sh.txt](https://github.com/user-attachments/files/17027592/build_and_install_fwupd.sh.txt)
[fwupd.txt](https://github.com/user-attachments/files/17027594/fwupd.txt)

**Comment by hwspeedy** [comment]
@terryn94 

I noted that DIMM spd is not working out of the box on an SMBus I801 adaptor with DDR3 (Old system :) )
kernel module at24 is missing on PCLinuxOS, so probably the same for all DDR3.

**QUICK-FIX:**
manually edit /etc/init.d/hardinfo2 and add "modprobe -q eeprom;" where the other modprobes are.
echo "alias spd eeprom" >/etc/modprobe.d/spd.conf
reboot and start hardinfo2 - go to memory devices - at the bottom is now SPD info.

**Comment by terryn94** [comment]
OK, I will look into it ;-)
