### ISSUE TITLE
Kubuntu 22.04 GTK2 package cannot be installed

### ISSUE THREAD

**Issue by ocerman** [hardinfo2/hardinfo2#5]
When the deb package is generated for GTK2, the package cannot be installed on Kubuntu 22.04 amd64 - it complains that the dependency cannot be resolved: `libgtk-2-0`.

I believe that the correct package for *Ubuntu 22.04 should be `libgtk2.0-0`

**Comment by mckaygerhard** [comment]
yes te package should be libgtk2.0-0 cos winbuntu is on top of a debian based package mantainership process.. will be fixed soon..

**Comment by hwspeedy** [comment]
Thanx for feedback, much appreciated. 

ubuntu 22.04 has GTK3, please use that.

**GTK2 is only for very old distro like rh6/ol6/c6. - GTK2 is unmaintained for many years!**

I will fix this and make it very clear that this is **very unsupported and not to be used by any distro.**

**Comment by mckaygerhard** [comment]
i can valid this.. @hwspeedy  cos i already used gtk2 for LXDE builds.. yeah its unmantained but is already working on LXDE distros.. i already proposed a pull request for.. please acept it!

**Comment by hwspeedy** [comment]
@ocerman The fix is added to master repo and tested on ubuntu22.04.

@mckaygerhard  PR is closed - that did not take into account of RPM.

**Always remember that the 90% users are the main target for any app**

PS: rPI-1 is one of my test machines - works and so does the rock p1s which is has smaller memory but 4 cores.

**Comment by mckaygerhard** [comment]
but @hwspeedy  what about making a debian package for GTK" the generation of the package still will be wrong! i meant its still an issue! and about 99% of users.. take into consideration that still we are not the 99% of such cases cos hardinfo1 still its used in distros and its also used as GTK2 cos there is already users that likes GTK2

**Comment by hwspeedy** [comment]
@mckaygerhard 

**It's very simple GTK2 is unmaintained - DEAD.**

**Debian will have only 1 version of hardinfo2 and that is with GTK3.**

**Comment by mckaygerhard** [comment]
its very simple debian jessie or debian 8 uses gtk2 as primary gtk and is mantained at freexian LTS

my laptop TOCHIVA 205 dont support more modern linuxkernel.. it haNDS DUE UNSUPORTED HARDWARE (developers dont continue due lack of hardware to test so i an using debian jessie)

many people still use GTK2 for many apps.. and you already builds a GTK2 package.. that juswt dont work due bad dependency

men! its just a change and people are contributing.. cut off just arging "its not supported" when we already knows that the problems its not GTK2 its just being agains the contribution behaviour.. 

i upload my laptop video with working harinfo 1

https://github.com/hardinfo2/hardinfo2/assets/1571724/073aafb0-570a-414e-8fea-c965b10fd7da

**Comment by diazvictor** [comment]
> **It's very simple GTK2 is unmaintained - DEAD.**

It's ok to close it if nobody wants to solve it, but if someone collaborates and solves it you should accept the patch.

**Comment by hwspeedy** [comment]
@mckaygerhard 
I made it possible to do you own unsupported build for now - that might break with next release.
