### ISSUE TITLE
Bug: Second stick of RAM missing

### ISSUE THREAD

**Issue by Lalarian** [hardinfo2/hardinfo2#51]
Hello!

I just used hardinfo 2.1.11 on my up to date arch system and noticed and issue in the memory section, where only one of two identical sticks of RAM where recognized in my notebook:
![grafik](https://github.com/hardinfo2/hardinfo2/assets/5146616/9a043b91-c0b9-42e6-8faa-92ae160a5ca7)

The notebook overall has 64GByte RAM (minus a bit for the CPU's internal graphics).

The benchmarks also show only 32GByte RAM:
![grafik](https://github.com/hardinfo2/hardinfo2/assets/5146616/a09c7ab0-d1b9-49e1-afff-7a2f54d0310b)

In XFCE's Taskmanager you can see there actually are 64GByte (and working):
![grafik](https://github.com/hardinfo2/hardinfo2/assets/5146616/463ded53-f9f4-41bb-a7e9-6015c381608b)

Would be nice if this could be fixed!
Thank you for the nice tool :)

**Comment by hwspeedy** [comment]
Please check that the memory is correctly detected by BIOS:
sudo dmidecode -t memory

**Comment by hwspeedy** [comment]
No answer
