### ISSUE TITLE
Cannot copy commands from action banners.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [hardinfo2/hardinfo2#62]
> ![Screenshot_20240812_203420](https://github.com/user-attachments/assets/93f070a2-9b17-44d0-8c5c-46bcd12cc76d)

I should be able to copy the commands from this, instead of write them manually. It'll be less error-prone for users, and quicker for longer commands.

**Comment by hwspeedy** [comment]
Just add the specific hardware settings/commands once to your /etc/rc.local file and you are done.

Please use discussion for ideas to gather people to create some code for a PR
Please keep issues clean with only real issues to avoid a huge backlog that no one wants to touch, thanx.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/hardinfo2/hardinfo2/issues/62#issuecomment-2284831076

@hwspeedy, so all FRs should be submitted at https://github.com/hardinfo2/hardinfo2/discussions/new?category=q-a? Irrespective, I thought that this was a bug, but thanks for the triage.

> https://github.com/hardinfo2/hardinfo2/issues/62#event-13854250216

Worth closing as unplanned, since it's not been remediated.

**Comment by hwspeedy** [comment]
Feature requests must appeal to FOSS developers to be made by someone other than the reporter - many are not and will therefore just sit forever - This I think is one of the dust collectors. 
Most people will probably not care about the extra DIMM information or do sudo, and those who take the time to configure their system will do the 2 lines in /etc/rc.local.
Therefor discussions are great to gain momentum and avoid issues growing with non important issues.
