### ISSUE TITLE
DRAM module  manufacturer ID code problem

### ISSUE THREAD

**Issue by csycsa** [hardinfo2/hardinfo2#66]
Hi, first of all thanks for this tool.     
Kimtigo is a  company of DRAM module  manufacturer.It's DRAM module  manufacturer ID code of  JEDEC is 89 68.On the Linux system terminal command line，type"dmidecode -t memory"，It can be correctly displayed as Kimtigo.But when using hardinfo2，It's incorrectly displayed as UNKNOWN [0968].
[内存产品在linux系统hardinfo2软件不显示我司厂商ID不良分析 (1).pptx](https://github.com/user-attachments/files/16658405/linux.hardinfo2.ID.1.pptx)
Thanks in advance.

**Comment by hwspeedy** [comment]
**Already in next (Master Unstable).**

1. The vendor database has been updated. https://github.com/hardinfo2/hardinfo2/commit/c4362ac311e7557c50ba6355b7a12ff20794445e
2. The memory SPD part has also been updated with service that should allow SPD info in hardinfo2, when run as user. 

**test**
Can you follow the build instructions and package a new version to test it? - see https://github.com/hardinfo2/hardinfo2/blob/master/README.md#building-and-installing
Remember to use get_unstable_master.sh

Another thread is here: (Status: Confusion about testing - WIP)
 https://github.com/hardinfo2/hardinfo2/commit/27179eb8fb12ccef9d369435aa462fe9d6256031#commitcomment-145321852

**Comment by hwspeedy** [comment]
Difference in ID is because you include the parity check at bit 8 - only lower 7 bit are used for bank and index.
Bank 9 index 0x68 - which is correct (Jedec vendor database currently has 13 banks with 128 entries)

See spd-decode.c line 712 for more info.

**Comment by csycsa** [comment]
Thanks for your help,I will test it as far as I can.

**Comment by csycsa** [comment]
CMake Error at deps/ggears2/CMakelists.txt:3 (find package):
By not providing "Findots.cmake" in CMAKE MODULE PATH this project has
asked CMake to find a package configuration file provided by "Qt5", but
CMake did not find one.
db
Could not find a package configuratton file provided by "ot5" with any of
the following names:
Qt5config.cmake
gt5.config.cmake
Add the installation prefix of "Ot5" to CMAKE PREFIX PATH or set "OtS DIR"
to a directory containing one of the above files. If "ot5" provides a
separate development package or SDK, be sure it has been installed.

**Comment by csycsa** [comment]
CMake Error at deps/ggears2/CMakelists.txt:3 (find package):
By not providing "Findots.cmake" in CMAKE MODULE PATH this project has
asked CMake to find a package configuration file provided by "Qt5", but
CMake did not find one.
db
Could not find a package configuratton file provided by "ot5" with any of
the following names:
Qt5config.cmake
gt5.config.cmake
Add the installation prefix of "Ot5" to CMAKE PREFIX PATH or set "OtS DIR"
to a directory containing one of the above files. If "ot5" provides a
separate development package or SDK, be sure it has been installed.
