### ISSUE TITLE
Gentoo app-admin/hardinfo2 Packaging Update

### ISSUE THREAD

**Issue by hwspeedy** [hardinfo2/hardinfo2#74]
Hi @thesamesam @quincyf467

Hardinfo has been released after >10 years without releases as community edition hardinfo2.

News:
• Lots of Maintenance/testing/doc/bugfixing and updating for current distros
• Keeping it working for ~10 years of old distros and tools
• New Benchmarks that works from slow to fast machines
• Added themes and dark/light mode
• Remade the lost website
• Lots of UI/UX improvements -> Refreshed

We are trying to get all distro in sync, so we have a common base in hardinfo2 for all distros.

Please update Gentoo, thanx.

Project homepage: https://hardinfo2.org/
Gentoo Linux packaging: https://github.com/hardinfo2/hardinfo2/issues/74
Release notes: https://github.com/hardinfo2/hardinfo2/releases/tag/release-2.1.14
Github: https://github.com/hardinfo2/hardinfo2/

**Comment by quincyf467** [comment]
I'll keep maintaining it in the GURU repository for now.

**Comment by hwspeedy** [comment]
Okay, Thank you very much!

If any problems for Gentoo just let me know or submit changes, thanx.
