### ISSUE TITLE
Hardinfo2 and metainfo in app centers - Updating for all distros

### ISSUE THREAD

**Issue by hwspeedy** [hardinfo2/hardinfo2#75]
Hi @hosiet and @topazus,

The hardinfo2 app is missing in all app stores/centers for fedora++ and debian++/ubuntu++

I guess that some of the problem is a **missing metainfo for appstream**?

I have added the following metainfo https://github.com/hardinfo2/hardinfo2/commit/51dd049659170da530ab3b559ef7fd2f080d4358

But when you manually install the package - it does not have an icon under installed apps, nor is it found in store - probably needs to be in repo but could be other mistakes...

In some stores, you have to manually add distro repo - is flatpak that important that the distro packages are not selected!! - Any explanation?

It should be found by benchmark, system, info, information, linux, hardware, hw, drivers, sysinfo, hwinfo, bench, etc. Don't know where to put keywords...

If you have knowledge about the distros and could check up on this issue, it would be great, thanx.

/hwspeedy

**Comment by topazus** [comment]
Yes, adding the metainfo file can make the software show up in Gnome software.

[1] https://github.com/GNOME/gnome-software/blob/main/doc/app-developers.md
[2] https://gitlab.gnome.org/GNOME/gnome-software/-/wikis/Software-metadata

**Comment by hwspeedy** [comment]
Thanx,

I have added more text as that must be the search keywords. Also added links for different url types found in the metainfo folder.

The icon appears when calling the gnome-software with the test params where you manually specify the icon, so I hope it does the same when released - maybe taken from the desktop file, which is linked in the metainfo.

https://github.com/hardinfo2/hardinfo2/commit/dfa1f49cd52ca51b5dd2cd62407607177b6cda50

/hwspeedy

**Comment by hwspeedy** [comment]
@hosiet, thanx for the fast update to debian sid.

**Good news: the hardinfo2 can now be found in debian sid unstable - THANX!**

**Improvements:**
It would be nice with an updated metainfo in hardinfo2 git so every distro gets the same, that they all like. Please comment and submit patches for appstream metainfo, thanx.

1. There are no pictures
   - I tested on fedora rawhide, which showed pictures when hardinfo2 was installed.
   - Do they need to be uploaded somewhere? - currently hardinfo2.org
   - Maybe another format - currently webp
   
2. The info is different, which spawns a couple of problems: 
    - hardinfo2 cannot be found by searching for eg. sysinfo (Still on MAC and was 25 years ago in Linux - good common name for what hardinfo2 does) etc.
    - hardinfo2 also works on tables and phones running Linux - benchmarks are already in the database..
    - The project license is GPL2+ and does support community development and changes.
    - Is the online database common for all distros? - maybe @topazus knows?

3. when installed and updating software center it shows as 2 programs

I had complete uninstalled hardinfo2 before installing it from software center, so it probably has one from an online database? and the one put into metainfo folder.
Maybe it's a bug in software center - handling distro repo installed and local installed wrongly...
PS: I have no local installed versions...


1 + 2) first (maybe hosiet's) edition (maybe from online database), second original
![another](https://github.com/user-attachments/assets/3b9e2076-fb08-49ec-9893-75f29f120a8d)
![original](https://github.com/user-attachments/assets/c55bc552-3d78-4fe4-9933-537f0cbf7d5d)

2-1)
![image](https://github.com/user-attachments/assets/0f146ed2-3761-4eb6-b86a-9d36e900063d)

3)
![2found](https://github.com/user-attachments/assets/e6e1dd93-0c9e-4540-9cee-76a67c9c7d5e)

**Comment by topazus** [comment]
https://github.com/hardinfo2/hardinfo2/blob/82d7bc1c6927bba254ac63bddb7d8e952330c691/tools/org.hardinfo2.hardinfo2.metainfo.xml#L31

No valid tag named forum, see https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-url

You can check the metainfo file with `appstream-util validate-relax --nonet org.hardinfo2.hardinfo2.metainfo.xml`

**Comment by hwspeedy** [comment]
@topazus - Thanx, suggest changing forum to contact for github discussion as we have help for userguide and faq - wants ordinary users to stay on hardinfo2.org (github is for development) - okay?

NOTE: "vcs-browser" and "contribute" tags are pretty new apparently - not in Ubuntu 20.04 LTS

I will try to add some mayor languages with the appstream-util, when we have looked at the other stuff and has one that we all like.

**Comment by hwspeedy** [comment]
> The value of the <image/> tag is a direct HTTP/HTTPS URL to a screenshot uploaded to a public location on the web. Images should ideally be provided in the PNG format; using JPEG or WebP is also permitted for images in metainfo files.

Images should be fine with webp and located on hardinfo2.org according to documentation but seams this could all be too new for Debian? - Please help to ID problem...
Who controls the online database? - is it each distro branch?

I will convert them to PNG as that is noted as the best way.
Renaming the 3 images to appstream211.png,  appstream212.png,  appstream213.png - so we can have new images for later releases without updating older ones... (Version 2.1.x=21)

**For next release:**
Appstream PNG images on server: https://github.com/hardinfo2/server/commit/bcad8b39aa0d4da1a93536ab444fe761754cba7b
Changed AppStream metainfo.xml: https://github.com/hardinfo2/hardinfo2/commit/376f7f4ea77733c7fac5ba11941f216c77ea670d

Please continue inputs, thanx

**Comment by hwspeedy** [comment]
Thanx - the app center gui repo system seams more "complicated" then I would ever have expected.

Note: appstream moved development to https://github.com/ximion/appstream 

Seams the data for servers are per distro and each distro sets it up and generates their online database.

Debian might actually be creating their own metainfo using appstream-generator and totally ignoring the one from package according to this:
https://github.com/ximion/appstream-generator?tab=readme-ov-file#appstream-generator

I or hosiet probably have to do something to get the automatic appstream-generator to accept the one from package? @hosiet 


What is Fedora doing to create metainfo for app center? (The above link says the appstream generator is mostly used by debian)
Will you (topazus)  put the hardinfo2 metainfo into fedora database or how does that work? - Looking forward to see what the result is for Fedora app center :)

Maybe this is why my gui app center is so empty in most Linux distros - even though I can find the software in distro repos.....

**Comment by hosiet** [comment]
You generally don't need to worry about distros on appstream generator. They have good handling of it. In case you are interested in, check out https://wiki.debian.org/AppStream for Debian's case. Just TL;DR: Debian provides them via https://appstream.debian.org/ .

And why the software is not shown in App centers, you may ask? Normally for Debian users, all they need to do is to install the `appstream` package explicitly and then execute `apt update`. If the metadata is still not shown after that, it should be considered a bug; please submit a bug report. See https://wiki.debian.org/AppStream for more information.

As upstream software author, the sole and the most important thing that one should care about is correctly writing the AppStream `metainfo` XML file, and have it correctly installed. Just make sure that `org.hardinfo2.hardinfo2.metainfo.xml` is correctly provided together with the software, and the rest of the things should be handled correctly by the distro. Of course, thing might be different if the software is provided via other channels like Flatpak, etc.

**Comment by hwspeedy** [comment]
@hosiet Thanx for answers.

I see that missing metadata warning has disappeared from https://tracker.debian.org/pkg/hardinfo and now says 4 warnings for found metainfo - so appstream-generator data is probably late compared to unstable repo release. Fair enough - just need to know.

Saw new link to: https://appstream.debian.org/sid/main/issues/hardinfo2.html (Another great tool)
- It has the url tag "forum" error that @topazus also discovered, thanx.
- It complains about image file format, even though documentation says it supports webp and it worked on fedora RawHide. But that's no problem - I just need to know to work with the different distro systems.

These are fixed by above submits.

I have added the two hints (missing devinfo+rating) as in this patch: https://github.com/hardinfo2/hardinfo2/commit/704c57200fbd3467b7a410c87551756984cc876c

Tested by appstream-util validate-relax, thanx @topazus 

All these packaging verification tools, that debian and fedora have, are so great - the problem is you need to release before getting a result. But now it should be better for next release.

**Any other parts we should add/change in metainfo?**

**Comment by topazus** [comment]
> What is Fedora doing to create metainfo for app center? (The above link says the appstream generator is mostly used by debian)
> Will you (topazus) put the hardinfo2 metainfo into fedora database or how does that work? - Looking forward to see what the result is for Fedora app center :)

When appstream-data package is updated, I think hardinfo2 will be found on GNOME software. [1]

[1] https://discussion.fedoraproject.org/t/how-to-let-gnome-software-find-a-new-appstream-metainfo-file/77739/6
