### ISSUE TITLE
OpenGL benchmark fails to run or send data on sync

### ISSUE THREAD

**Issue by SonicBoone56** [hardinfo2/hardinfo2#84]
On some of my machines, I can run the OpenGL benchmark and receive scores properly. But if I run it via the sync tool, it usually doesn't run properly or fails to create a score. And usually if it does create a score, it fails to update it in the database or it produces really high outliers that aren't consistent with previous tests. I think it may have become broken in the latest version.

**Comment by hwspeedy** [comment]
Thanx for reporting your findings,

> I think it may have become broken in the latest version.

1. What versions of hardinfo2 are we talking about?

2. Please submit screen shoots of the failed OpenGL benchmark results.

3. Please submit screen shoots of display info for driver info for OpenGL for failing machines.

4. Distro?

**Comment by SonicBoone56** [comment]
I forgot to say that this also applies to the GPU drawing benchmark too. Version 2.1.13pre on Ubuntu 24.04.

**Comment by hwspeedy** [comment]
@SonicBoone56 
Please retest on the new hardinfo2 2.1.17/2.1.16 - I found an error in benchmark result data that prevented the data from being shown - I only saw that on GPU drawing - but this seams to be a combi of 3 changes made to latest release.

**Comment by SonicBoone56** [comment]
Issue has been fixed in the latest version! Still not sure how my desktop GPU somehow scores worse than old integrated graphics in the benchmark though. Also not sure why only two of my machines even run the OpenGL benchmark despite OpenGL games running on all of them.

**Comment by hwspeedy** [comment]
Let's debug - if you mark the benchmarks that you send in, we can find them and look at the details.
start "hardinfo2 -u debugGPU" and then press the synchronize and send a message here - then we can see more on what is going on.
you can see your online benchmarks as https://hardinfo2.org/?u=debugGPU
