### ISSUE TITLE
SVG-size

### ISSUE THREAD

**Issue by tutralex** [hardinfo2/hardinfo2#85]
- "bodhi.svg" is over 2 MB;
- "nobara.svg" is a simple logo, but over 140 KB;
- have you looked at your own logo "hardinfo2.svg", how badly and crookedly the paths are made there. Maybe this work is not worth AI?

**Comment by hwspeedy** [comment]
Hi tutralex,

Are you on a storage space limited distro?

Anyone is welcome to improve svg files...

**Comment by tutralex** [comment]
Hmm, well, I guess I'll get to it, at least I'll bring the most crazy and large SVGs into a normal form.

**Comment by tutralex** [comment]
If you are satisfied with my work, please include it in the project:
![hardinfo2](https://github.com/user-attachments/assets/511896c5-3b6c-46f1-9c65-859c8016029c)
![hardinfo2](https://github.com/user-attachments/assets/06479d29-d642-46ad-90b3-debdbe6c082d)
![bodhi](https://github.com/user-attachments/assets/9f1ff392-1e5d-41d9-a0a2-3f334c92a5ab)
![nobara](https://github.com/user-attachments/assets/3589dcd5-9201-423f-9967-9898736a1ed7)
![sysrescue](https://github.com/user-attachments/assets/3a31d850-43ba-4082-b5d0-a7e0add8299b)

**Comment by hwspeedy** [comment]
Thanx, they look so nice, good job. 

https://github.com/hardinfo2/hardinfo2/commit/0609a0b13399e84ec48e51c1197124d5411cfa8d
