### ISSUE TITLE
Missing license info for binaries under tools/spd-eeproms

### ISSUE THREAD

**Issue by hosiet** [hardinfo2/hardinfo2#88]
I noticed the addition of `tools/spd-eeproms/` directory, but I am not sure where those binaries come from. Could you add the origin information of those binaries somewhere (e.g., under `tools/LICENSES/` directory)?

This should include at least the author and the license info, and ideally also the info about how the binaries were generated.

**Comment by hwspeedy** [comment]
@hosiet - Thanx, submitted to [tools/LICENSES/](https://github.com/hardinfo2/hardinfo2/blob/master/tools/LICENSES/spd-test-eproms.txt) in master.

**Comment by hwspeedy** [comment]
@hosiet 
Can we update Debian with hardinfo 2.2.1 - I can see Debian package tracker does not pick up the new release - hence this ping. In advance Thanx.

https://tracker.debian.org/pkg/hardinfo2

**Please see security bug #93**
