### ISSUE TITLE
Stuck at configuration during installation on Ubuntu 22.04

### ISSUE THREAD

**Issue by jstumpin** [hardinfo2/hardinfo2#91]
Tried installing from [released package](https://github.com/hardinfo2/hardinfo2/releases/tag/release-2.1.16pre) as well as built from source (shown below is v2.1.18, but rest assured, v2.1.16 is all the same) but either way will presented with the following problem:

Term output upon running `sudo apt install ./hardinfo2*`:
```
Preparing to unpack .../hardinfo2_2.1.18-Ubuntu-22.04_amd64.deb ...
Unpacking hardinfo2 (2.1.18) ...
Setting up hardinfo2 (2.1.18) ...
Created symlink /etc/systemd/system/basic.target.wants/hardinfo2.service → /lib/
systemd/system/hardinfo2.service.

Progress: [ 60%] [##################################........................]
```

Content of `/var/log/dpkg.log`:
```
2024-10-14 14:01:20 status unpacked hardinfo2:amd64 2.1.18
2024-10-14 14:01:20 status half-configured hardinfo2:amd64 2.1.18
```

On a different machine (Intel CPU, the one with problem was AMD CPU) but same Ubuntu 22.04, the installation was successful. Had no issue with `hardinfo(1)`. Any pointers?

Thanks.

**Comment by jstumpin** [comment]
As a workaround, [disabling service](https://github.com/hardinfo2/hardinfo2/blob/master/CMakeLists.txt#L7):
`option(HARDINFO2_SERVICE "Build with service support" 1)`

**Comment by hwspeedy** [comment]
Try to see what your ubuntu 22.04 installation does not like about the service, which is just a couple of commands. 
Run the commands manually and find the command that stops on your installation. See tools/hardinfo2.service.

It's probably some I2C SPD module loading - but haven't seen that before. This depends on motherboard.

**Comment by hwspeedy** [comment]
Hi @jstumpin,

Any feedback on what was going wrong on you systems? - we cannot reproduce, so we need your input.

In advance thanx.
