### ISSUE TITLE
Security issue found by Matthias Gerstner

### ISSUE THREAD

**Issue by hwspeedy** [hardinfo2/hardinfo2#93]
**Matthias Gerstner has found a security issue**, which he says is low enough, that we can fix it in the open, so here we go:

**Security Problems**
1. Any part of the system should only write where root is the only one allowed to write.
2. It's not nice to change attributes on sysfs, even after opt-in.
3. The different services (SystemD, SystemV, RunIt) should call one single script
4. We need an opt-in to the extra information from distro using the root helper service.

**Use background for hardinfo2:**
The hardinfo2 program is used in GUI mode , CLI mode and remote CLI via eg. ansible.

**Suggestions - Thanx Matthias!**
One solution is pkexec to avoid system service, but would require user interaction also in scripts via pkttyagent. I feel this is too complicated for users.

Another solution is to opt-in by creating a hardinfo2 group that users can be added to in order to gain access to extra information.
I think this sounds acceptable for users.

An extension could be to use DBUS - I think this is a later step or we need someone to step forward fast.

**Changes to be done:** 
ad 1.
Services should use /run for data.
Fixed by https://github.com/hardinfo2/hardinfo2/commit/99bba62ca2681db7a9613c87c1afe081a28b08f9

ad 2.
Get DMI info (And only the part we need) stored in /run/hardinfo2/.. also to avoid need for DMI for memory slots/dimm info.
first part fixed by https://github.com/hardinfo2/hardinfo2/commit/b01cf95a43dc1f7f3861953c34e2feaab63c4d70
second part use info in hardinfo2 - fixed by https://github.com/hardinfo2/hardinfo2/commit/50e4037ec4100919154892433e39523b09acd1f3

ad 3.
Take out the commands to a script that is called by the 3 service types supported so far. Install along side hardinfo2.
Fixed by https://github.com/hardinfo2/hardinfo2/commit/b01cf95a43dc1f7f3861953c34e2feaab63c4d70

ad 4.
Add hardinfo2 group creation 
Fix service to store extra information files with root:hardinfo2 640 (root RW, hardinfo2 R, all none) 
Fixed by https://github.com/hardinfo2/hardinfo2/commit/b01cf95a43dc1f7f3861953c34e2feaab63c4d70
Allow directory traversing/listing https://github.com/hardinfo2/hardinfo2/commit/7344f53bfaa482204c34c1a0e984590e0a282b73

**Solution is after above changes:**
1. User installs hardinfo2 progam using root as normal. 
This installs program and the service that is run immediately, create group hardinfo2, which has access to extra info.

2. User can use the program and is missing information which is very nice - Like Memory Slot occupation, DIMM Memory Information, Resources iomem and ioports addresses.

3. A hint box (blue box at bottom) informs the user to add him self to the hardinfo2 group using sudo, if not already done.. - This is a onetime job to opt-in.

4. Then the program has full functionality running in user space only.

**Thanx to Matthias for all the help and suggestions**

-

**READY FOR TESTING AND COMMENTS**

**Comment by hwspeedy** [comment]
Affected released versions are 2.1.14 and 2.1.17

**Comment by hwspeedy** [comment]
Fixed in release 2.2.1

**Comment by Kieltux** [comment]
Thanks to @hwspeedy and Matthias Gerstner.
Updated packages for openSUSE are submitted.

**Comment by topazus** [comment]
I also bumped the package to 2.2.1 on Fedora and EPEL.

**Comment by yochananmarqos** [comment]
Manjaro and AUR packages are now updated as well.

**Comment by hosiet** [comment]
I genuinely think requesting the user to perform command-line-based `groupadd` is more complicated than invoking `pkexec`. At least with `pkexec` the user only needs to input their password when prompted.

With the current design, the distro maintainers will need to purge the created `hardinfo2` group when the package is removed. This is not necessarily a bad design, just more likely for maintainers to forget (and thus should be documented somewhere).

**Comment by hwspeedy** [comment]
@hosiet 
Do I remember correctly that you are not a hardinfo2 user?

The solution for now is a **one time opt in** instead of every time you use it - The extra info is ordinary PC info. Now some people think entering a password all the time is security - it's not!

This way allows for some distros to allow users access on (pre)install and sysadm to give eg. ansible remote user rights for extra info. 

It's also easy for system admins with group access.

**You should only remove hardinfo2 group on uninstall, and only if you want to do that - or leave it as the root/user optin is real.**
