### ISSUE TITLE
Executive order 14071 - GPL

### ISSUE THREAD

**Issue by hwspeedy** [hardinfo2/hardinfo2#95]
I have changed the hardinfo2 organization base permission to read until below crazy issue is answered by distros within the next couple of months.

Deadline: December 11, 2024 for compliance.

Seams to be a mayor issue for a lot of distros...

https://www.youtube.com/watch?v=L5Ec5jrpLVk&ab_channel=BryanLunduke

hardinfo2 accepts all pull requests (PR) until we are told by distros not to do that.
People are not removed from project until we are told by distros to do that.

/hwspeedy

**Comment by hwspeedy** [comment]
Lot's of if's and uncertainties - if Bryan is right, then distros might have to comply and so must all upstreams, which we will continue to be.
Until we have clear orders to do something from distros - not just someone, we are all just private coders having fun, with no political opinions or other stuff not important to code, thanx.

**Comment by tutralex** [comment]
Project frozen? I found a small bug (small buffer for some notifications) + one notification is not translated into other languages, wait until December 11?

**Comment by tutralex** [comment]
It turns out that you are not so free... No one has demanded anything from you yet, and you are already waiting for instructions from above?))

**Comment by tutralex** [comment]
@hwspeedy 
A small bug (small buffer for some notifications) + one notification is not translated into other languages.

**Comment by hwspeedy** [comment]
Removed 2 comments that had nothing to do with code. Please use reddit for that, thanx.

No hardinfo2 is not frozen - As you can read in the initial comment - Just do a pull request - which you where already asked to use instead of CI/CD (write access) due to lack of training in git usage. If you need help, just start an discussion on howto use fork, git and PR, thanx.

**Comment by tutralex** [comment]
@hwspeedy 
Уже обучился.

**Comment by hwspeedy** [comment]
No news from any distro - which is good news!

To enable smooth development we will again be using CI/CD (write access) for anyone, who wants to be part.
My short experience as maintainer tells that a Pull Request with the initial proposed changes, should be sufficient to ensure safe development and hence give write access to users. Just request write access on pull request, thanx.

The active project maintainer will read through all changes and send code comments or do reverts. Nothing will be released, that is not validated and tested. All members of projects, which includes distro packing, can see who has which access.

Happy coding!

/hwspeedy
